name: hopp
description: hopp — sosyal/tanışma uygulaması (WebView)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  location: ^5.0.3
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - hopp.png
    - hopp_foreground.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "hopp.png"
  adaptive_icon_background: "#0E7DFD"
  adaptive_icon_foreground: "hopp_foreground.png"
  remove_alpha_ios: true
